### ISSUE TITLE
Несколько вопросов о формате правил

### ISSUE THREAD

**Issue by mulya** [petrovich/petrovich-rules#15]
Формат правил довольно скудно описан и вызывает ряд вопросов, сейчас я их и озвучу.
###### В чём разница между exceptions и suffixes?
По всему выходит что всё оба раздела можно превратить в suffixes с указанием в документации того факта что порядок правил важен.
###### Действительно ли нужно было вводить новый раздел **tags**?
Сама цель ясна, но мне кажется что более универсальным решением было бы не добавление нового атрибута, а запись имеющегося атрибута **test** в форме регекспа (гасан-*) для всех имеющихся правил.

**PS** Понимаю что имея такое количество портов изменять формат правил - это жуткий головняк,  поэтому не настаиваю на действиях)

**Comment by dustalov** [comment]
В случае `exceptions` сопоставление ведётся по слову целиком, а в случае `suffixes` только по окончанию. Идея с метками (`tags`) позволила внедрить ряд эвристик. За два года проблем не возникало. Рекомендую использовать их в портах.
