### ISSUE TITLE
Поддержка библиотеки

### ISSUE THREAD

**Issue by dustalov** [petrovich/petrovich-rules#20]
Добрый день, хочу поднять вопрос о поддержке библиотеки.

Существует около десяти портов Petrovich на самые разные языки программирования. Создатели оригинальной версии для Ruby не вмешиваются в этот процесс и доверяют людям (@petrovich/porters), вложившим свои силы в перенос, тестирование и распространение портов. Это очень круто.

Порты связаны с единой базой морфологических правил, на поддержку которой требуется определённое время, которого сейчас у нас нет (@petrovich/owners). Таким образом, считаю целесообразным передать репозиторий `petrovich-rules` тому, кто:

1. сможет уделить некоторое время изредка появляющимся здесь багам и запросам;
2. организует тесты словаря путём вызова `rake evaluate` из оригинального Petrovich;
3. будет рад отметить это в своём резюме или сайте.

Предлагаю обсудить и прийти к решению. Кандидатуры принимаются в комментариях.

**Comment by arbox** [comment]
@dustalov , как я понимаю, речь идет об интеграционном тестировании для всех портов?

**Comment by dustalov** [comment]
@arbox не совсем: речь о поддержке только словаря, который используется всеми портами.

**Comment by mikhail-barg** [comment]
Возможно к осуждению стоит присовокупить мое предложение о единой базе тестов: https://github.com/petrovich/petrovich-ruby/issues/49
Чем дальше, тем больше мне кажется, что тестовые наборы должны жить в проекте с правилами (и обновляться совместно).

Соответственно, если поскольку проект на руби это - reference implementation, то автоматические тесты в проекте правил должны запускать руби-версию. А остальные порты будут запускать тесты в своих проектах.

**Comment by dustalov** [comment]
Да, так и есть. Я завтра кое-что подготовлю.

**Comment by dustalov** [comment]
Обнаружил, что проблема #21 блокирует процесс.

**Comment by dustalov** [comment]
Сделал для ветки `v1` автоматический запуск `rake evaluate` для проверки качества. Пока ожидается, что разработчики будут сравнивать долю правильных ответов до и после самостоятельно и добросовестно.

**Comment by mikhail-barg** [comment]
ЗдОрово, но не совсем понятно, как именно это должно работать. Как мне запустить этот тест для моего PR?

**Comment by dustalov** [comment]
GitHub автоматически запускает тесты для новых PR. Попробуйте добавить пустой коммит и сделать push.

**Comment by mikhail-barg** [comment]
Спасибо, я почему-то думал, что он и для старых запустит. Что в общем-то было безосновательно.

**Comment by dustalov** [comment]
Возобновить активность удалось. @ujifgc и @mikhail-barg, спасибо за работу!
