### ISSUE TITLE
Единственная ветка

### ISSUE THREAD

**Issue by dustalov** [petrovich/petrovich-rules#21]
Обнаружил, что имеются две разные ветки: `master` и `v1`, содержащие совершенно разные данные. Реорганизация репозиториев невозможна без устранения одной из них.

**Comment by mikhail-barg** [comment]
Я так понимаю, что эта ситуация не нова, описана она тут: https://github.com/petrovich/petrovich-ruby/issues/48

По идее, ветка `v1` должна заменить master, но только когда все пОрты на нее перейдут. На сколько я вижу, ни один из портов (кроме референсоного руби) этого не сделал. В порте C# я вопрос о переходе поднимал еще в апреле (https://github.com/petrovich/petrovich-net/issues/10). Никто так и не откликнулся, что стало одним из аргументов в пользу создания отдельного C#-порта.

В итоге, ветка `v1` существует с марта, и движений в сторону перехода на нее не видно. Так что откладывать реорганизацию репозиториев до гипотетического перехода всех проектов на нее, представляется напрасным.

**Comment by dustalov** [comment]
Именно эту проблему я и предлагаю обсудить в этой задаче во избежание дальнейших недоразумений. Возможно, эвристики следует вынести в отдельный файл для сохранения обратной совместимости.

**Comment by mikhail-barg** [comment]
Не могу придумать другого решения для сохранения обратной совместимости. Так что я за отдельный файл с правилами для определения пола.
