### ISSUE TITLE
Добавить в Travis вызов остальных тестов из /petrovich-eval

### ISSUE THREAD

**Issue by mikhail-barg** [petrovich/petrovich-rules#29]
И дать возможность просмотреть ошибки по аналогии с основными правилами.

**Comment by mikhail-barg** [comment]
Как я уже писал в другом тикете, поскольку у нас появилась общая база тестов, хотелось бы иметь референсные результаты для всех тестовых файлов. Сейчас в [логе трависа](https://travis-ci.org/petrovich/petrovich-rules) видно, что прогоняются только файлы `surnames.tsv` и `surnames.gender.tsv`, при этом список ошибок виден только по `surnames.tsv`.

Мне представляется, что было бы полезно следующее:
1. Включить в тесты все файлы из `petrovich/petrovich-eval`
2. Для каждого из файлов сделать `cat filename_errors.tsv` (чтобы можно было сравнивать свои результаты с референсными).
3. Возможно как-то более удобно публиковать референсные результаты (строки вида `Sum of the 100816 correct examples and 164 mistakes is 100980.`), чтобы можно было скармливать их в CI для других проектов. Хотя тут я не уверен, что конкретно будет удобным — я еще не смотрел, как именно это можно внедрить в CI. Возможно тут будет достаточно файлов `*_errors.tsv`.

@dustalov  что скажете?

**Comment by mikhail-barg** [comment]
Также не совсем понятно, будет ли Travis отрабатывать в случае обновлений в `petrovich/petrovich-eval`. На сколько я сейчас вижу - этого не происходит. Хотелось бы, чтобы тесты прогонялись и в случае обновления правил, и в случае обновления тестов.

**Comment by mikhail-barg** [comment]
@dustalov Дмитрий, хотел бы привлечь ваше внимание к этому тикету. Очень огорчает отсутствие возможности сравнивать результаты с референсной версией по всем тестовым файлам.

**Comment by dustalov** [comment]
@mikhail-barg, ничего себе, я первый раз вижу эту запись. GitHub должны сделать что-то с уведомлениями, ими невозможно пользоваться.

Не совсем понимаю, при чём здесь `petrovich-rules`, если речь идёт о `petrovich-eval`. Сейчас мне некогда этим заниматься, но я не буду возражать против реализации предложенной функциональности. @petrovich/core

**Comment by dustalov** [comment]
У меня нашлась свободная минутка и я добавил проверку по `{firstnames,midnames,surnames}.tsv`.
