### ISSUE TITLE
Конвертировать gender.json из gender.yml

### ISSUE THREAD

**Issue by mikhail-barg** [petrovich/petrovich-rules#32]
Я бы хотел вмержить последние изменения в структуре правил определения пола в свой проект, но мне нужен актуальный json-файл. Для rules.json вроде конверсия из yml делается автоматически. Сделайте пожалуйста аналогичную систему и для gender.json

**Comment by ujifgc** [comment]
Оба файла генерируются: https://github.com/petrovich/petrovich-rules/blob/master/Rakefile. Сгенерировал.

**Comment by mikhail-barg** [comment]
Спасибо!
