### ISSUE TITLE
Неверное склонение фамилии "Дарвин"

### ISSUE THREAD

**Issue by mikhail-barg** [petrovich/petrovich-rules#33]
В творительном падеже должно быть "Дарвином", сейчас - "Дарвиным".
При этом понятно, что например для фамилии "Ильин" в творительном падеже "Ильиным" — это правильно.
![default](https://cloud.githubusercontent.com/assets/2208971/22860729/b1562992-f117-11e6-8ebd-f06affaeee0f.png)

**Comment by dustalov** [comment]
@mikhail-barg есть возможность прислать PR?
