### ISSUE TITLE
Опечатка в README.md (один или дефис)

### ISSUE THREAD

**Issue by installero** [petrovich/petrovich-rules#37]
> На что заменять - mods. Массив модификаторов. Модификатор может иметь впереди **один или дефис**, он означает количество символов, которые нужно будет вырезать из слова.

Что имелось ввиду? Я вижу у модификаторов один или несколько минусов.

**Comment by dustalov** [comment]
Это опечатка. Нужно исправить `README.md`. Один дефис удаляет один символ с конца слова. Два дефиса удаляют два символа с конца слова, и так далее.

Например: `-я` удаляет символ в конце слова и добавляет туда букву «я».
