### ISSUE TITLE
several cases of incorrect declination

### ISSUE THREAD

**Issue by sszuev** [petrovich/petrovich-rules#46]
- `Ия,Ии,Ие,Ию,Ией,Ие` src: https://github.com/petrovich4j/petrovich4j/issues/5 (односложные имена, оканчивающиеся на -ия,  [imena.org/decl_fn.html](http://imena.org/decl_fn.html), [gramota.ru/slovari/info/ag/sklon/](http://gramota.ru/slovari/info/ag/sklon/) 3.12 - спорно; два способа, видимо не стоит менять, **отмена**)
- `Муромец,Муромца,Муромцу,Муромца,Муромцем,Муромце` https://github.com/petrovich4j/petrovich4j/issues/6 (**PR**)
- `Санёк,Санька,Саньку,Санька,Саньком,Саньке` https://github.com/petrovich4j/petrovich4j/issues/7 (**PR**)
- `Рашель`: https://github.com/petrovich4j/petrovich4j/issues/9 (все же склоняется - [gramota.ru/slovari/info/ag/sklon/](http://gramota.ru/slovari/info/ag/sklon/) 4.15, **отмена**)
-  "-ав" (Богослав\Богуслав):`Богуслав,Богуслава,Богуславу,Богуслава,Богуславом,Богуславе`, see [analizfamilii.ru/Boguslav/](https://www.analizfamilii.ru/Boguslav/skloneniye.html) (**PR**)
- (female?) last-name `Младшая`, `Молодшая` ([сомнения](https://github.com/petrovich/petrovich-rules/pull/50#issuecomment-740591226) -> **отмена**)
- `Белорусец` - [analizfamilii.ru/Belorusets/](https://www.analizfamilii.ru/Belorusets/skloneniye.html) `Белорусца, Белорусцу, Белорусца, Белорусцом, Белорусце` (**PR**)

.

**Comment by dustalov** [comment]
Вопрос в силе или можно закрыть?

**Comment by sszuev** [comment]
close (для дефектов вещей - новые ишью).
