### ISSUE TITLE
Пара неверных склонений в городах

### ISSUE THREAD

**Issue by OlegPasko** [petrovich/petrovich-rules#9]
Привет.
Пробую использовать руби-гем для склонения названий городов в ледующем контексте:
Рим — о Риме
Париж — о Париже
В большинстве городов всё отлично, но есть пара исключений:
Ханой — о Ханом (нужно о Ханое)
Бангкок — о Бангкке (нужно о Бангкоке)

**Comment by dustalov** [comment]
За два года вопрос не поднимался. Будем считать, что актуальность утрачена. Закрываю задачу.

**Comment by vickodin** [comment]
@OlegPasko подскажите пожалуйста, на каком варианте склонений названий городов вы остановились в результате?

Заранее благоадарю!

**Comment by OlegPasko** [comment]
@vickodin , я уже точно не помню, мы вроде бы просто хаки на нашей стороне для исключений впихнули тогда )
